name: Actualizar Lista de Asistencias Escolares de Hoy

on:
  # Ejecución manual desde GitHub
  workflow_dispatch:
    inputs:
      nivel:
        description: "Nivel educativo"
        required: true
        type: choice
        options:
          - "P"
          - "S"
        default: "P"
      grado:
        description: "Grado"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
        default: "1"
      seccion:
        description: "Sección (opcional - si no se especifica, procesa todas las secciones)"
        required: false
        type: string
        default: ""

  # Ejecución desde solicitud HTTP externa
  repository_dispatch:
    types: [actualizar-listas-asistencia-hoy]

jobs:
  actualizar-lista-asistencias:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Instalar dependencias
        run: npm install

      - name: Validar parámetros de entrada
        id: validar-parametros
        run: |
          # Determinar origen de los parámetros
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Ejecutión manual detectada"
            NIVEL="${{ github.event.inputs.nivel }}"
            GRADO="${{ github.event.inputs.grado }}"
            SECCION="${{ github.event.inputs.seccion }}"
          elif [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "Ejecución por HTTP detectada"
            NIVEL="${{ github.event.client_payload.nivel }}"
            GRADO="${{ github.event.client_payload.grado }}"
            SECCION="${{ github.event.client_payload.seccion }}"
          else
            echo "❌ Tipo de evento no soportado: ${{ github.event_name }}"
            exit 1
          fi

          # Limpiar y validar sección (opcional)
          if [ -n "$SECCION" ]; then
            # Convertir a mayúsculas y limpiar espacios
            SECCION=$(echo "$SECCION" | tr '[:lower:]' '[:upper:]' | tr -d ' ')
            
            # Validar formato de sección (solo letras A-Z)
            if [[ ! "$SECCION" =~ ^[A-Z]+$ ]]; then
              echo "❌ Error: Sección debe contener solo letras (A-Z)"
              echo "Sección recibida: '$SECCION'"
              exit 1
            fi
            
            echo "✅ Sección especificada: '$SECCION'"
          else
            echo "ℹ️ No se especificó sección - procesará todas las secciones"
            SECCION=""
          fi

          # Validar nivel
          if [[ ! "$NIVEL" =~ ^[PS]$ ]]; then
            echo "❌ Error: Nivel debe ser 'P' (Primaria) o 'S' (Secundaria)"
            echo "Nivel recibido: '$NIVEL'"
            exit 1
          fi

          # Validar grado
          if [[ ! "$GRADO" =~ ^[1-6]$ ]]; then
            echo "❌ Error: Grado debe estar entre 1 y 6"
            echo "Grado recibido: '$GRADO'"
            exit 1
          fi

          # Validar combinación nivel-grado
          if [ "$NIVEL" = "P" ] && [[ ! "$GRADO" =~ ^[1-6]$ ]]; then
            echo "❌ Error: Para primaria, el grado debe estar entre 1 y 6"
            exit 1
          fi

          if [ "$NIVEL" = "S" ] && [[ ! "$GRADO" =~ ^[1-5]$ ]]; then
            echo "❌ Error: Para secundaria, el grado debe estar entre 1 y 5"
            exit 1
          fi

          echo "✅ Parámetros validados: Nivel=$NIVEL, Grado=$GRADO, Sección='$SECCION'"
          echo "nivel=$NIVEL" >> $GITHUB_OUTPUT
          echo "grado=$GRADO" >> $GITHUB_OUTPUT
          echo "seccion=$SECCION" >> $GITHUB_OUTPUT

      - name: Mostrar información de ejecución
        run: |
          echo "🚀 === INFORMACIÓN DE EJECUCIÓN ==="
          echo "Evento: ${{ github.event_name }}"
          echo "Nivel: ${{ steps.validar-parametros.outputs.nivel }}"
          echo "Grado: ${{ steps.validar-parametros.outputs.grado }}"
          if [ -n "${{ steps.validar-parametros.outputs.seccion }}" ]; then
            echo "Sección: ${{ steps.validar-parametros.outputs.seccion }}"
          else
            echo "Sección: (todas las secciones)"
          fi
          echo "Actor: ${{ github.actor }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
          echo "Fecha: $(date)"
          echo "================================"

      - name: Ejecutar script de actualización
        run: |
          echo "📋 Ejecutando script de actualización de listas de asistencias..."

          # Construir comando base
          COMANDO="npx ts-node ./src/jobs/transactions/TransaccionAsistenciasEscolaresRDP05_a_RDP01.ts ${{ steps.validar-parametros.outputs.nivel }} ${{ steps.validar-parametros.outputs.grado }}"

          # Agregar sección si está especificada
          if [ -n "${{ steps.validar-parametros.outputs.seccion }}" ]; then
            COMANDO="$COMANDO ${{ steps.validar-parametros.outputs.seccion }}"
            echo "Ejecutando: $COMANDO"
          else
            echo "Ejecutando: $COMANDO (sin sección específica)"
          fi

          # Ejecutar comando
          eval $COMANDO
        env:
          # Google Drive (RDP01)
          RDP01_GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.RDP01_GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          RDP01_GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.RDP01_GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY }}
          RDP01_GOOGLE_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.RDP01_GOOGLE_SERVICE_ACCOUNT_PROJECT_ID }}
          RDP01_GOOGLE_DRIVE_ROOT_SHARED_FOLDER_ID: ${{ secrets.RDP01_GOOGLE_DRIVE_ROOT_SHARED_FOLDER_ID }}
          # PostgreSQL (RDP02)
          RDP02_INS1_DATABASE_URL: ${{ secrets.RDP02_INS1_DATABASE_URL }}
          RDP02_INS2_DATABASE_URL: ${{ secrets.RDP02_INS2_DATABASE_URL }}
          RDP02_INS3_DATABASE_URL: ${{ secrets.RDP02_INS3_DATABASE_URL }}
          # MongoDB (RDP03)
          RDP03_INS1_DATABASE_URL: ${{ secrets.RDP03_INS1_DATABASE_URL }}
          RDP03_INS2_DATABASE_URL: ${{ secrets.RDP03_INS2_DATABASE_URL }}
          RDP03_INS3_DATABASE_URL: ${{ secrets.RDP03_INS3_DATABASE_URL }}
          RDP03_INS4_DATABASE_URL: ${{ secrets.RDP03_INS4_DATABASE_URL }}
          RDP03_INS5_DATABASE_URL: ${{ secrets.RDP03_INS5_DATABASE_URL }}

          # Redis (RDP05)
          RDP05_INS1_REDIS_BD_BASE_URL_API: ${{ secrets.RDP05_INS1_REDIS_BD_BASE_URL_API }}
          RDP05_INS1_REDIS_BD_TOKEN_FOR_API: ${{ secrets.RDP05_INS1_REDIS_BD_TOKEN_FOR_API }}
          RDP05_INS2_REDIS_BD_BASE_URL_API: ${{ secrets.RDP05_INS2_REDIS_BD_BASE_URL_API }}
          RDP05_INS2_REDIS_BD_TOKEN_FOR_API: ${{ secrets.RDP05_INS2_REDIS_BD_TOKEN_FOR_API }}
          RDP05_INS3_REDIS_BD_BASE_URL_API: ${{ secrets.RDP05_INS3_REDIS_BD_BASE_URL_API }}
          RDP05_INS3_REDIS_BD_TOKEN_FOR_API: ${{ secrets.RDP05_INS3_REDIS_BD_TOKEN_FOR_API }}

          # API03
          API03_URL_BASE: ${{ secrets.API03_URL_BASE }}

          # Entorno
          ENTORNO: ${{ secrets.ENTORNO }}

      - name: Reporte de resultado
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ === EJECUCIÓN EXITOSA ==="
            echo "Lista de asistencias actualizada correctamente"
            echo "Nivel: ${{ steps.validar-parametros.outputs.nivel }}"
            echo "Grado: ${{ steps.validar-parametros.outputs.grado }}"
            if [ -n "${{ steps.validar-parametros.outputs.seccion }}" ]; then
              echo "Sección: ${{ steps.validar-parametros.outputs.seccion }}"
            else
              echo "Sección: (todas las secciones procesadas)"
            fi
          else
            echo "❌ === EJECUCIÓN FALLIDA ==="
            echo "Error al actualizar lista de asistencias"
            echo "Revisar logs anteriores para más detalles"
            exit 1
          fi
